workflow:
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'
      when: never
    - if: $CI_COMMIT_BRANCH == "master"
      variables:
        TAG_NAME: apps1
      when: always
   
 
stages:
- deploy
deploy:
  stage: deploy
  tags:
    - ${TAG_NAME}
  script:
  - docker compose down
  - docker rmi yandex_direct_api_working-app
  - docker compose up -d
