version: "3.8"

services:
  app:
    build: .
    environment:
      TZ: Europe/Moscow
      ECOMRU_PG_DB_NAME: ${ECOMRU_PG_DB_NAME}
      ECOMRU_PG_HOST: ${ECOMRU_PG_HOST}
      ECOMRU_PG_PORT: ${ECOMRU_PG_PORT}
      ECOMRU_PG_USER: ${ECOMRU_PG_USER}
      ECOMRU_PG_PASSWORD: ${ECOMRU_PG_PASSWORD}
      ECOMRU_PG_SSL_MODE: ${ECOMRU_PG_SSL_MODE}
      YA_TEST_TOKENS: ${YA_TEST_TOKENS}
      YA_TEST_USERS: ${YA_TEST_USERS}

    command: sh script.sh
    #volumes:
     #   - ./logs:/app/Project/logs
    


    
